spring:
  application:
    name: voluntrix-backend

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  sql:
    init:
      mode: always

  api-docs:
    enabled: true
    path: /v3/api-docs
  
  swagger-ui:
    path: /swagger-ui.html
  


